default_platform(:android)

platform :android do

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end

  desc "Submit a new internal version"
  lane :internal do
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/apk/release/app-release.apk',
      json_key_data: ENV['PLAY_STORE_CONFIG_JSON'],
      )
  end

end
