name: Build Pull Request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
env:
  API_URL_DEV: ${{secrets.API_URL_DEV}}
  KEYSTORE: ${{secrets.KEYSTORE}}
  KEYSTORE_PASS: ${{secrets.KEYSTORE_PASS}}
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: 'stable'
          flutter-version: '2.2.3'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test
      
      - name: Configure keystore
        run: echo "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
      
      - name: Build APK
        run: flutter build apk --dart-define=API_URL="$API_URL_DEV"

      - name: Setup Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
          working-directory: android

      - name: Push beta release to Google Playstore
        run: bundle exec fastlane internal
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      - name: Upload apk to the artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
