name: Build Pull Request
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
env:
  API_URL_DEV: ${{secrets.API_URL_DEV}}
  KEYSTORE: ${{secrets.KEYSTORE}}
  KEYSTORE_PASS: ${{secrets.KEYSTORE_PASS}}
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.1

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: dart format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test
      
      - name: Configure keystore
        run: echo "$KEYSTORE" | base64 --decode > android/app/upload-keystore.jks
      
      - name: Build APK
        run: flutter build apk --dart-define=API_URL="$API_URL_DEV"

      - name: Upload apk to the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
