name: Build
on:
  push:
    branches:
      - develop
      - master
  pull_request:
  workflow_dispatch:
  
jobs:
  build:
    name: Flutter Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
